version: '3' #指定版本
services:    #服务根节点
  mysql:
    image: mysql
    command: [
      '--default-authentication-plugin=mysql_native_password',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go
#      MYSQL_USER: springboot
#      MYSQL_PASSWORD: springboot
    ports:
      - "3306:3306"
#    volumes:
#      - ./setting/db/init.sql:/docker-entrypoint-initdb.d/init.sql
#      - ./setting/db/init_data.sql:/docker-entrypoint-initdb.d/init_data.sql
  #      - ./server/mysql/common:/var/lib/mysql #留下數據，就算container關了還是有資料存在